### ISSUE TITLE
Mail merge APIs do not download output file after completing the merging

### ISSUE THREAD

**Issue by gianglv** [asposeforcloud/Aspose_Cloud_SDK_For_Python#10]
I tried to run a mail merge task using MailMerge.execute and MailMerge.execute_template but afterward cannot get the output file. The APIs only download the template file after completing the merge and return the template file name.

I think user should be able to get output file after execute mail merge.

**Comment by assadvirgo** [comment]
Hello,

Sorry for the inconvenience. Will investigate the problem.

Thanks

**Comment by assadvirgo** [comment]
@gianglv,

Thanks for reporting the problem. We've updated the methods to download appropriate file.
