### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by quietlyconfident** [asposeforcloud/Aspose_Cloud_SDK_For_Python#8]
Installing the program with:

````
pip install asposecloud
````

and then trying to import the module, as suggested in the documentation, 

````
>>> import asposecloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named asposecloud
````

fails.  Looking at what is installed in `~/.virtualenvs/test/lib/python2.7/site-packages/asposecloud` , it appears there is no `__init__.py` file installed into the main directory.  The `setup.py` file needs to be fixed so that it installs the bits inside of the asposecloud directory.

Though I see tests included in this repository, I can't believe that they are working if the library itself is not importable.  I suspect that one of the following is true:

1. The tests are not being run automatically on each commit and/or before each release,
2. The tests are being run, but they are being run against the source tree (which does have an `__init__.py` file in the right place); so they aren't picking up that the installed library is broken; or 
3. The tests are being run on an installed version of the library, but it is being installed in such a way that it only overwrites changed files, it doesn't delete files that have been removed.

I suggest:

1. The tests should be run automatically by a CI system on each commit.
2. The first step in the test should be to create a brand new virtual environment into which only asposecloud is installed.
3. When the tests are executed, the source tree should not be in the path.

I wouldn't normally write such a long issue here, but reinstalling this module broke my running application, which is pretty annoying since I pay for the cloud API service.  Please fix this ASAP.

**Comment by assadvirgo** [comment]
Hello

Did you update the package or it happend after uninstall and then reinstall the same release. 

I'm looking into the issue.

Thanks

**Comment by assadvirgo** [comment]
Merged and updated the package.
